version: 2

defaults: &defaults
  working_directory: ~/ci-cd
  docker:
    - image: circleci/node:8
cypress: &cypress
  working_directory: ~/ci-cd
  docker:
    - image: cypress/base:8
restore_node_modules: &restore_node_modules
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - v1-dependencies-{{ .Branch }}-
      - v1-dependencies-

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          name: save dependencies cache
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/ci-cd
          paths:
            - vue-test-utils/
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ci-cd
      - *restore_node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: unit
          command: npm run test:unit
  teste2e:
    <<: *cypress
    steps:
      - attach_workspace:
          at: ~/ci-cd
      - *restore_node_modules
      - run:
          name: e2e
          command: npm run test:e2e:headless

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - teste2e:
          requires:
            - build
